# Agent port configuration
admin:
    default: 1666

dns:
    default: 1609

ftp:
    web1: 11201
    web2: 11202

mysql:
    web1: 11001
    web2: 11002

vhost:
    web1: 1801
    web2: 1802

socks:
    web1: 1501
    web2: 1502
